# Generated by Django 4.1.7 on 2023-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_clicks_wthasapp', models.IntegerField(verbose_name='clicks_whatsapp')),
            ],
        ),
    ]
